name: infracost

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  infracost:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Infracost breakdown
        uses: infracost/actions@v3
        with:
          path: .
          format: json
          out-file: infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Upload to Infracost
        uses: infracost/actions@v3
        with:
          command: upload
          path: infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
